### ISSUE TITLE
不好使

### ISSUE THREAD

**Issue by lushtree-cn-honeyzhao** [NYSamnang/react-native-light-confirm#1]
根本就不好使

**Comment by NYSamnang** [comment]
@honeyzhaoAliyun Sorry to hear that! If something made you inconvenient please kindly add a feature request. I'm feel free to upgrade for you :).

**Comment by nysamnang** [comment]
@honeyzhaoAliyun  Sorry to hear that! If something made you inconvenient please kindly add a feature request. I'm feel free to upgrade for you :)

**Comment by nysamnang** [comment]
@honeyzhaoAliyun I just updated to **version 1.1.0**. Hope you enjoy it :)
#https://github.com/NYSamnang/react-native-light-confirm/tree/1.1.0
